-- Describe OGRENCI
CREATE TABLE "ogrenci" ("id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "no" INTEGER NOT NULL , "sinif" VARCHAR NOT NULL , "adsoyad" VARCHAR NOT NULL )


-- Describe ODUNC
CREATE TABLE "odunc" ("id" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL , "no" INTEGER NOT NULL , "sinif" VARCHAR NOT NULL , "adsoyad" VARCHAR NOT NULL , "veren" VARCHAR NOT NULL , "verme_tarihi" DATETIME NOT NULL , "alan" VARCHAR, "alma_tarihi" DATETIME, "kitap" VARCHAR NOT NULL )

